
#pragma once

#include <AP_HAL/AP_HAL_Boards.h>

#ifndef AP_BCM_ENABLED
#define AP_BCM_ENABLED (HAL_MAX_CAN_PROTOCOL_DRIVERS && HAL_PROGRAM_SIZE_LIMIT_KB > 1024)
#endif

#ifndef AP_M1DCB2450SC_ENABLED
#define AP_M1DCB2450SC_ENABLED 1
#endif
